image: "ruby:2.5.1"

before_script:
    - apt-get update -qq && apt-get install -y -qq sqlite3 libsqlite3-dev nodejs
    - ruby -v
    - gem update --system
    - gem install bundler --no-ri --no-rdoc
    - bundle install
    - bundle exec rubocop
   
rspec:
    script:
        - bundle exec rake spec
