language: ruby
sudo: required
dist: trusty

addons:
  chrome: stable
cache:
  bundler: true

before_install:
  - gem update --system
  - gem install bundler
  - google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 http://localhost &

rvm:
  - 2.5.1

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - ENGINE_CART_RAILS_OPTIONS='--skip-git --skip-bundle --skip-listen --skip-spring --skip-yarn --skip-keeps --skip-action-cable --skip-coffee --skip-puma --skip-test'
    - MAILSERVER='smtp.example.com'
    - MAILUSER='test@example.com'
    - MAILPASS='word'
    - SERVERNAME='localhost'
    - NFS_DIR='tmp'

script:
  - bundle exec rake ci

services:
  - redis-server
before_script:
  - jdk_switcher use oraclejdk8
