language: ruby
rvm:
 - 2.5.1
sudo: required # temporary travis-recommended workaround, routes to older (known to work) env
cache: bundler
dist: trusty
git:
    submodules: false
env:
  MYSQL_DB_HOST=127.0.0.1
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - ENGINE_CART_RAILS_OPTIONS='--skip-git --skip-bundle --skip-listen --skip-spring --skip-yarn --skip-keeps --skip-action-cable --skip-coffee --skip-puma --skip-test'
addons:
  apt:
   sources:
    - mysql-5.7-trusty
   packages:
    - mysql-server
    - mysql-client
  chrome: stable

before_install:
  - gem update --system
  - gem install bundler
  - google-chrome-stable --headless --disable-gpu --no-sandbox --remote-debugging-port=9222 http://localhost &

# before_install:
#   - mysql -e 'CREATE DATABASE hyraxdb_test;'

before_script:
  - jdk_switcher use oraclejdk8
  - cp config/database.yml config/databse.tmp.yml
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database hyraxdb_test'
  - bundle exec rubocop
script:
  - xvfb-run -a bundle exec rake ci
after_script:
  - cp config/database.tmp.yml config/database.yml #this will revert to the normal state.
services:
  - redis-server
