# Simple yaml config-driven schema which is used to define model attributes,
# index key names, and form properties.
#
# Attributes must have a type but all other configuration options are optional.
# Please note: If using Valkyrie's Fedora Metadata Adapter, predicates for attributes
# must be placed here.
#
# attributes:
#   attribute_name:
#     type: string
#     multiple: false
#     index_keys:
#       - "attribute_name_sim"
#     form:
#       required: true
#       primary: true
#       multiple: false
#
# @see config/metadata/basic_metadata.yaml for an example configuration
#
# Generated via
#  `rails generate hyrax:work_resource GenericWork`

attributes:
  award:
    type: string
    predicate: "http://id.loc.gov/ontologies/bibframe/awards"
    multiple: false
    index_keys:
      - "award_sim"
    form:
      required: false
      primary: true
      multiple: false
  includes:
    type: string
    predicate: "http://purl.org/dc/terms/hasPart"
    multiple: false
    index_keys:
      - "includes_sim"
    form:
      required: false
      primary: true
      multiple: false
  alternate_title:
    type: string
    predicate: "http://purl.org/dc/terms/alternative"
    multiple: false
    index_keys:
      - "alternate_title_sim"
    form:
      required: false
      primary: true
      multiple: false
  digitization_date:
    type: string
    predicate: "http://purl.org/dc/terms/date#digitized"
    multiple: false
    index_keys:
      - "digitization_date_sim"
    form:
      required: false
      primary: true
      multiple: false
  series:
    type: string
    predicate: "http://opaquenamespace.org/ns/seriesName"
    multiple: false
    index_keys:
      - "series_sim"
    form:
      required: false
      primary: true
      multiple: false
  event:
    type: string
    predicate: "http://purl.org/dc/terms/coverage"
    multiple: false
    index_keys:
      - "event_sim"
    form:
      required: false
      primary: true
      multiple: false
  year:
    type: string
    predicate: "http://purl.org/dc/terms/date"
    multiple: false
    index_keys:
      - "year_sim"
    form:
      required: false
      primary: true
      multiple: false
  extent:
    type: string
    predicate: "http://purl.org/dc/terms/extent"
    multiple: false
    index_keys:
      - "extent_sim"
    form:
      required: false
      primary: true
      multiple: false
  school:
    type: string
    predicate: "http://vivoweb.org/ontology/core#College"
    multiple: false
    index_keys:
      - "school_sim"
    form:
      required: false
      primary: true
      multiple: false
  citation:
    type: string
    predicate: "http://purl.org/dc/terms/bibliographicCitation"
    multiple: false
    index_keys:
      - "citation_sim"
    form:
      required: false
      primary: true
      multiple: false
  editorial_note:
    type: string
    predicate: "http://www.w3.org/2004/02/skos/core#editorialNote"
    multiple: false
    index_keys:
      - "editorial_note_sim"
    form:
      required: false
      primary: true
      multiple: false
